name: "Release"

on: push
  #workflow_run:
    #workflows: ["Tex format CI"]
    #types: [completed]
    #branches: "main"
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  #release:
  on-success:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: Create directory
      run: |
        rm -rf .build
        mkdir .build
    - name: Build pdfs
      run: |
        find src -name '*.tex' -exec pdflatex {} \;
        mv *.pdf .build
    - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        #- name: Commit report
        #  run: |
        #    git config --global user.name 'Thomas Lohse'
        #    git config --global user.email 't-lohse@users.noreply.github.com'
        #    git add .build 
        #    git commit -m ".build"
        #    git push

